# Generated by Django 3.0 on 2023-04-18 13:15

from django.db import migrations


def copy_data(apps, schema_editor):
    try:
        OldAddress = apps.get_model("oc_lettings_site", "Address")
        OldLetting = apps.get_model("oc_lettings_site", "Letting")
    except LookupError:
        # The old app isn't installed.
        return

    NewAddress = apps.get_model("lettings", "Address")
    NewAddress.objects.bulk_create(
        [
            NewAddress(
                number=old_object.number,
                street=old_object.street,
                city=old_object.city,
                state=old_object.state,
                zip_code=old_object.zip_code,
                country_iso_code=old_object.country_iso_code,
            )
            for old_object in OldAddress.objects.all()
        ]
    )

    NewLetting = apps.get_model("lettings", "Letting")
    NewLetting.objects.bulk_create(
        [
            NewLetting(
                title=old_object.title,
                address=NewAddress.objects.get(
                    number=old_object.address.number,
                    street=old_object.address.street,
                    city=old_object.address.city,
                    state=old_object.address.state,
                    zip_code=old_object.address.zip_code,
                    country_iso_code=old_object.address.country_iso_code,
                ),
            )
            for old_object in OldLetting.objects.all()
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "0002_alter_address_options"),
    ]

    operations = [
        migrations.RunPython(copy_data, migrations.RunPython.noop),
    ]
