# Generated by Django 4.2 on 2023-04-19 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel("Address"),
        migrations.DeleteModel("Letting"),
        migrations.DeleteModel("Profile"),
    ]
